language: c
compiler: gcc
sudo: required

before_install:
#  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
#  - sudo apt-get -qq update
#  - sudo apt-get install $COMPILER dkms

  - export ALL_DEB=$(wget --quiet -O - ${KERNEL_URL}v${KVER}/ | grep -o 'href=".*"' | grep -m1 all | cut -d '"' -f 2)
  - export KVER_BUILD=$( echo $ALL_DEB | grep -o '[a-z0-9]*\.[0-9]*\_all\.deb' | cut -d '.' -f 1)
  - wget ${KERNEL_URL}v${KVER}/$(wget --quiet -O - ${KERNEL_URL}v${KVER}/ | grep -o 'href=".*"' | grep headers | grep generic | grep -m1 amd64 | cut -d '"' -f 2)
  - wget ${KERNEL_URL}v${KVER}/$ALL_DEB
  - sudo dpkg -i *.deb

#env:
#  matrix:
#  - COMPILER=gcc-5 KVER=4.13.1-041301 KVER_TS=201709100232
#  - COMPILER=gcc-4.9 KVER=4.13.1-041301 KVER_TS=201709100232
#  - COMPILER=gcc-5 KVER=4.4.87-040487 KVER_TS=201709070334
#  #- COMPILER=gcc-5 KVER=3.16.0-77-generic
#  - COMPILER=gcc-4.9 KVER=3.16.47-031647 KVER_TS=201708260658

script:
  - gcc --version
  - make CC=$COMPILER KVER=$KVER-$KVER_BUILD-generic

env:
  global:
    - KERNEL_URL=http://kernel.ubuntu.com/~kernel-ppa/mainline/

#addons:
#  apt:
#    packages: &base_build
#      - lynx

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      env: COMPILER=gcc-5 KVER=4.13.1
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
      env: COMPILER=gcc-6 KVER=4.13.1
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
      env: COMPILER=gcc-5 KVER=4.4.87
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
      env: COMPILER=gcc-4.9 KVER=3.16.47
